# Generated by Django 4.2.5 on 2023-10-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
